import {
  Utensils,
  Home,
  Car,
  HeartPulse,
  GraduationCap,
  PartyPopper,
  ShoppingBag,
  ShoppingCart,
  Receipt,
  Repeat,
  MoreHorizontal,
  Wallet,
  Briefcase,
  TrendingUp,
  Gift,
  Plane,
  Dumbbell,
  Gamepad2,
  Coffee,
  Fuel,
  Wifi,
  Phone,
  PawPrint,
  Baby,
  Shirt,
  Film,
  Book,
  Bus,
  Bike,
  Stethoscope,
  CreditCard,
  PiggyBank,
  Landmark,
  Banknote,
  Music,
  Smartphone,
  Droplet,
  Zap,
  Tv,
  Tag,
  type LucideIcon,
} from "lucide-react";

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  utensils: Utensils,
  home: Home,
  car: Car,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  "party-popper": PartyPopper,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  receipt: Receipt,
  repeat: Repeat,
  "more-horizontal": MoreHorizontal,
  wallet: Wallet,
  briefcase: Briefcase,
  "trending-up": TrendingUp,
  gift: Gift,
  plane: Plane,
  dumbbell: Dumbbell,
  gamepad: Gamepad2,
  coffee: Coffee,
  fuel: Fuel,
  wifi: Wifi,
  phone: Phone,
  "paw-print": PawPrint,
  baby: Baby,
  shirt: Shirt,
  film: Film,
  book: Book,
  bus: Bus,
  bike: Bike,
  stethoscope: Stethoscope,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  landmark: Landmark,
  banknote: Banknote,
  music: Music,
  smartphone: Smartphone,
  droplet: Droplet,
  zap: Zap,
  tv: Tv,
};

export const ICON_OPTIONS = Object.keys(ICON_REGISTRY);

export function getIcon(key: string | null | undefined): LucideIcon {
  if (!key) return Tag;
  return ICON_REGISTRY[key] ?? Tag;
}
